config/routes.rb
Twitter::Application.routes.draw do
  resources :users
  resources :tweets
  resources :sessions

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :presence => true
  validates :password, :presence => true
  has_many :tweets

  def send_instructions
    Notifier.instructions(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   private
  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to "/users", alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(:username => params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to("/tweets")
      flash[:notice] = "User succesfully logged in"
    else
      flash[:notice] = "Invalid log in"
      render("new")
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to("/tweets")
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_filter :authorize, only: [:create]

  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to("/tweets")
    else
      flash[:alert] = "Invalid entries, please try again"
      render("new")
    end
  end

  def edit
  end

  def show
    @tweet = Tweet.find(params[:id])
    @tweet = Tweet.new
  end


private
  def tweet_params
    params.require(:tweet).permit(:status)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end


  def index
    @user = User.new
    @users = User.all
  end

def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User succesfully created"
      redirect_to("/tweets")
    else
      alert[:notice] = "Invalid entries, try again please"
      render("index.html.erb")
    end
  end

  def edit
  end

  def show
  end

  private
    def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div id="user_header">
    <%= link_to "Home", tweets_path %>  |

    <% if current_user %>
      Logged in as <%= current_user.username %>
      <%= link_to "Log Out", session_path("current"), method: "delete" %> |

      <% else %>
        <%= link_to "Log in", new_session_path %>  |
        <%= link_to "Sign Up", users_path %>  |
        <% end %>
  </div>
  <%= bootstrap_flash %>

  <%= yield %>
</div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for @tweets do |f| %>
  <% if @tweet.errors.any? %>
    <div class="error_messages">
      <h2 class="error">Form is invaid</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= Status %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :status %></br>
    <%=f.text_area :status, size: "25x10" %>
  </div>

  <%= f.submit("Submit", :class => "btn btn-default") %>
  <% end %>

app/views/tweets/index.html.erb
<h1 class="green">TwitterClone</h1>


<%= link_to "New Tweet", new_tweet_path, :class => "btn btn-default" %>
<h3>Tweets:</h3>

<ul>
  <% @tweets.each do |tweet| %>
    <li><%= link_to tweet.status, tweet_path(tweet.id) %></li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1>Create a Status</h1>

<%= render 'form' %>

app/views/tweets/show.html.erb
<h2><%= @tweet.status %></h2>


<p class="thread"><%= @tweet.tweet %></p>

<%= render './tweets/form' %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2 class="error">Form is invaid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :username %></br>
    <%=f.text_field :username %>
  </div>
  <div class="form-group">
    <%= f.label :password %></br>
    <%=f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %></br>
    <%=f.password_field :password_confirmation %>
  </div>
  <%= f.submit("Sign up", :class => "btn btn-default") %>
  <% end %>

app/views/users/index.html.erb
<h1>Log in or sign up</h1>

<%= render 'form' %>

<ul>
  <% @user.tweets.each do |tweet| %>
    <li><%= tweet.status %></li>
  <% end %>
</ul>